name: Build and Test
on:
 push:
  branches: [master]
 pull_request:
   branches: [master]
jobs:
  test:
    runs-on: alpine:latest
    steps:
    - name: checkout code
      uses: actions/checkout@v4
