name: Build and Test
on:
 push:
  branches: [master]
 pull_request:
   branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: setup JDK
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '17'
        distribution: 'oracle'
    - name: Maven clean Install
      run: |
        cd helloworld
        mvn clean install package
        cd ..
    - name: Docker logging
      uses: docker/login-action@v3
      with:
        username: svmani218
        password: Manikanta110
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.3.0
      with:
        context: .
        push: true
        tags: svmani218/helloworld:v1
      
