name: Build and Test
on:
 push:
  branches: [master]
 pull_request:
   branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: setup JDK
      uses: actions/setup-java@v4.2.1
      with:
        java-version: '17'
        distribution: 'oracle'
    - name: Maven clean Install
      run: |
        cd helloworld
        mvn clean install
